application:
  clients:
    - username: micha32
      password: admin
      roles: ADMIN
    - username: josegomez
      password: admin
      roles: READ,WRITE
    - username: guest
      password: guest
      roles: USER